---
functional:
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Требование Пользователь должен иметь возможность фильтровать товары
non-functional:
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
implicit:
  - Сайт должен быть интуитивно понятным и простым для использования 
  - Важно обеспечить быструю работу сайта без задержек
  - Сайт должен быть адаптирован для работы на различных по размеру экрана мобильных устройствах
  - Сайт должен сохранять корзину пользователя после перезагрузки страницы 
